Metrics/LineLength:
  Max: 120

Metrics/ClassLength:
  Max: 400

Metrics/ModuleLength:
  Max: 400

Metrics/MethodLength:
  Max: 40

Metrics/AbcSize:
  Max: 40

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 15
